---
- hosts: localhost
  connection: local

  tasks:
    - ansible.builtin.import_tasks: tasks/repositories.yml
    - ansible.builtin.import_tasks: tasks/packages.yml
    - ansible.builtin.import_tasks: tasks/tools.yml
    - ansible.builtin.import_tasks: tasks/gnome-setup.yml
    - ansible.builtin.import_tasks: tasks/work.yml
