---
- name: Change user shell to zsh
  become: true
  vars:
    current_user: "{{ ansible_user_id }}"
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: /bin/zsh
- name: Install Oh-My-Zsh
  ansible.builtin.shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
- name: Install NVM
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | PROFILE=/dev/null bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
- name: Copy ZSH configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
  loop:
    - ../files/.zshrc
    - ../files/.zshenv
